### ISSUE TITLE
0 flagellum system

### ISSUE THREAD

**Issue by raphik12** [CyberCRI/Hero.Coli#262]

**Comment by leilasatsou** [comment]
Coucou Raphaël,
Y a t-il moyen que tu me supprimes des notifications ? Vu que je ne travailles plus au gamelab...
Merci d'avance !
Bonne soirée.
Envoyé depuis Yahoo Mail pour Android

**Comment by raphik12** [comment]
Salut @leilasatsou 
Comme tu veux, ou bien tu demandes à Jesse ou à la personne qui t'a ajoutée à CyberCRI de t'enlever, ou bien tu gères tes notifications sur ton compte, cf https://help.github.com/articles/managing-notification-delivery-methods/
