### ISSUE TITLE
Connection with Google Account

### ISSUE THREAD

**Issue by eldarne** [CyberCRI/Hero.Coli#414]
Works fine on Chrome, but takes a very long time to connect on firefox

**Comment by raphik12** [comment]
How fast does it connect on Firefox with other websites? Does it connect significantly slower on Herocoli than on those other websites?
Is the game properly displayed in Chrome? Doesn't work at all on my computer.

**Comment by raphik12** [comment]
this feature was discarded since the device ID that was already generated and managed will be enough to analyze data.
